# Generated by Django 4.2.1 on 2023-06-15 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_timer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timer',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
